/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as WafPoliciesIndexRouteImport } from "./routes/waf-policies/index"
import { Route as TenantsIndexRouteImport } from "./routes/tenants/index"
import { Route as SyncSecretsIndexRouteImport } from "./routes/sync-secrets/index"
import { Route as RoutesIndexRouteImport } from "./routes/routes/index"
import { Route as LoadBalancersIndexRouteImport } from "./routes/load-balancers/index"
import { Route as EnvoyProxyIndexRouteImport } from "./routes/envoy-proxy/index"
import { Route as ConfigurationIndexRouteImport } from "./routes/configuration/index"
import { Route as WafPoliciesNameRouteImport } from "./routes/waf-policies/$name"
import { Route as TenantsNameRouteImport } from "./routes/tenants/$name"
import { Route as SyncSecretsNamespaceNameRouteImport } from "./routes/sync-secrets/$namespace.$name"
import { Route as RoutesNamespaceNameRouteImport } from "./routes/routes/$namespace.$name"
import { Route as LoadBalancersNamespaceNameRouteImport } from "./routes/load-balancers/$namespace.$name"
import { Route as EnvoyProxyNamespaceNameRouteImport } from "./routes/envoy-proxy/$namespace.$name"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const WafPoliciesIndexRoute = WafPoliciesIndexRouteImport.update({
  id: "/waf-policies/",
  path: "/waf-policies/",
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsIndexRoute = TenantsIndexRouteImport.update({
  id: "/tenants/",
  path: "/tenants/",
  getParentRoute: () => rootRouteImport,
} as any)
const SyncSecretsIndexRoute = SyncSecretsIndexRouteImport.update({
  id: "/sync-secrets/",
  path: "/sync-secrets/",
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesIndexRoute = RoutesIndexRouteImport.update({
  id: "/routes/",
  path: "/routes/",
  getParentRoute: () => rootRouteImport,
} as any)
const LoadBalancersIndexRoute = LoadBalancersIndexRouteImport.update({
  id: "/load-balancers/",
  path: "/load-balancers/",
  getParentRoute: () => rootRouteImport,
} as any)
const EnvoyProxyIndexRoute = EnvoyProxyIndexRouteImport.update({
  id: "/envoy-proxy/",
  path: "/envoy-proxy/",
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationIndexRoute = ConfigurationIndexRouteImport.update({
  id: "/configuration/",
  path: "/configuration/",
  getParentRoute: () => rootRouteImport,
} as any)
const WafPoliciesNameRoute = WafPoliciesNameRouteImport.update({
  id: "/waf-policies/$name",
  path: "/waf-policies/$name",
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsNameRoute = TenantsNameRouteImport.update({
  id: "/tenants/$name",
  path: "/tenants/$name",
  getParentRoute: () => rootRouteImport,
} as any)
const SyncSecretsNamespaceNameRoute =
  SyncSecretsNamespaceNameRouteImport.update({
    id: "/sync-secrets/$namespace/$name",
    path: "/sync-secrets/$namespace/$name",
    getParentRoute: () => rootRouteImport,
  } as any)
const RoutesNamespaceNameRoute = RoutesNamespaceNameRouteImport.update({
  id: "/routes/$namespace/$name",
  path: "/routes/$namespace/$name",
  getParentRoute: () => rootRouteImport,
} as any)
const LoadBalancersNamespaceNameRoute =
  LoadBalancersNamespaceNameRouteImport.update({
    id: "/load-balancers/$namespace/$name",
    path: "/load-balancers/$namespace/$name",
    getParentRoute: () => rootRouteImport,
  } as any)
const EnvoyProxyNamespaceNameRoute = EnvoyProxyNamespaceNameRouteImport.update({
  id: "/envoy-proxy/$namespace/$name",
  path: "/envoy-proxy/$namespace/$name",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/tenants/$name": typeof TenantsNameRoute
  "/waf-policies/$name": typeof WafPoliciesNameRoute
  "/configuration/": typeof ConfigurationIndexRoute
  "/envoy-proxy/": typeof EnvoyProxyIndexRoute
  "/load-balancers/": typeof LoadBalancersIndexRoute
  "/routes/": typeof RoutesIndexRoute
  "/sync-secrets/": typeof SyncSecretsIndexRoute
  "/tenants/": typeof TenantsIndexRoute
  "/waf-policies/": typeof WafPoliciesIndexRoute
  "/envoy-proxy/$namespace/$name": typeof EnvoyProxyNamespaceNameRoute
  "/load-balancers/$namespace/$name": typeof LoadBalancersNamespaceNameRoute
  "/routes/$namespace/$name": typeof RoutesNamespaceNameRoute
  "/sync-secrets/$namespace/$name": typeof SyncSecretsNamespaceNameRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/tenants/$name": typeof TenantsNameRoute
  "/waf-policies/$name": typeof WafPoliciesNameRoute
  "/configuration": typeof ConfigurationIndexRoute
  "/envoy-proxy": typeof EnvoyProxyIndexRoute
  "/load-balancers": typeof LoadBalancersIndexRoute
  "/routes": typeof RoutesIndexRoute
  "/sync-secrets": typeof SyncSecretsIndexRoute
  "/tenants": typeof TenantsIndexRoute
  "/waf-policies": typeof WafPoliciesIndexRoute
  "/envoy-proxy/$namespace/$name": typeof EnvoyProxyNamespaceNameRoute
  "/load-balancers/$namespace/$name": typeof LoadBalancersNamespaceNameRoute
  "/routes/$namespace/$name": typeof RoutesNamespaceNameRoute
  "/sync-secrets/$namespace/$name": typeof SyncSecretsNamespaceNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/tenants/$name": typeof TenantsNameRoute
  "/waf-policies/$name": typeof WafPoliciesNameRoute
  "/configuration/": typeof ConfigurationIndexRoute
  "/envoy-proxy/": typeof EnvoyProxyIndexRoute
  "/load-balancers/": typeof LoadBalancersIndexRoute
  "/routes/": typeof RoutesIndexRoute
  "/sync-secrets/": typeof SyncSecretsIndexRoute
  "/tenants/": typeof TenantsIndexRoute
  "/waf-policies/": typeof WafPoliciesIndexRoute
  "/envoy-proxy/$namespace/$name": typeof EnvoyProxyNamespaceNameRoute
  "/load-balancers/$namespace/$name": typeof LoadBalancersNamespaceNameRoute
  "/routes/$namespace/$name": typeof RoutesNamespaceNameRoute
  "/sync-secrets/$namespace/$name": typeof SyncSecretsNamespaceNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/tenants/$name"
    | "/waf-policies/$name"
    | "/configuration/"
    | "/envoy-proxy/"
    | "/load-balancers/"
    | "/routes/"
    | "/sync-secrets/"
    | "/tenants/"
    | "/waf-policies/"
    | "/envoy-proxy/$namespace/$name"
    | "/load-balancers/$namespace/$name"
    | "/routes/$namespace/$name"
    | "/sync-secrets/$namespace/$name"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/tenants/$name"
    | "/waf-policies/$name"
    | "/configuration"
    | "/envoy-proxy"
    | "/load-balancers"
    | "/routes"
    | "/sync-secrets"
    | "/tenants"
    | "/waf-policies"
    | "/envoy-proxy/$namespace/$name"
    | "/load-balancers/$namespace/$name"
    | "/routes/$namespace/$name"
    | "/sync-secrets/$namespace/$name"
  id:
    | "__root__"
    | "/"
    | "/tenants/$name"
    | "/waf-policies/$name"
    | "/configuration/"
    | "/envoy-proxy/"
    | "/load-balancers/"
    | "/routes/"
    | "/sync-secrets/"
    | "/tenants/"
    | "/waf-policies/"
    | "/envoy-proxy/$namespace/$name"
    | "/load-balancers/$namespace/$name"
    | "/routes/$namespace/$name"
    | "/sync-secrets/$namespace/$name"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TenantsNameRoute: typeof TenantsNameRoute
  WafPoliciesNameRoute: typeof WafPoliciesNameRoute
  ConfigurationIndexRoute: typeof ConfigurationIndexRoute
  EnvoyProxyIndexRoute: typeof EnvoyProxyIndexRoute
  LoadBalancersIndexRoute: typeof LoadBalancersIndexRoute
  RoutesIndexRoute: typeof RoutesIndexRoute
  SyncSecretsIndexRoute: typeof SyncSecretsIndexRoute
  TenantsIndexRoute: typeof TenantsIndexRoute
  WafPoliciesIndexRoute: typeof WafPoliciesIndexRoute
  EnvoyProxyNamespaceNameRoute: typeof EnvoyProxyNamespaceNameRoute
  LoadBalancersNamespaceNameRoute: typeof LoadBalancersNamespaceNameRoute
  RoutesNamespaceNameRoute: typeof RoutesNamespaceNameRoute
  SyncSecretsNamespaceNameRoute: typeof SyncSecretsNamespaceNameRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/waf-policies/": {
      id: "/waf-policies/"
      path: "/waf-policies"
      fullPath: "/waf-policies/"
      preLoaderRoute: typeof WafPoliciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/tenants/": {
      id: "/tenants/"
      path: "/tenants"
      fullPath: "/tenants/"
      preLoaderRoute: typeof TenantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/sync-secrets/": {
      id: "/sync-secrets/"
      path: "/sync-secrets"
      fullPath: "/sync-secrets/"
      preLoaderRoute: typeof SyncSecretsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/routes/": {
      id: "/routes/"
      path: "/routes"
      fullPath: "/routes/"
      preLoaderRoute: typeof RoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/load-balancers/": {
      id: "/load-balancers/"
      path: "/load-balancers"
      fullPath: "/load-balancers/"
      preLoaderRoute: typeof LoadBalancersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/envoy-proxy/": {
      id: "/envoy-proxy/"
      path: "/envoy-proxy"
      fullPath: "/envoy-proxy/"
      preLoaderRoute: typeof EnvoyProxyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/configuration/": {
      id: "/configuration/"
      path: "/configuration"
      fullPath: "/configuration/"
      preLoaderRoute: typeof ConfigurationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/waf-policies/$name": {
      id: "/waf-policies/$name"
      path: "/waf-policies/$name"
      fullPath: "/waf-policies/$name"
      preLoaderRoute: typeof WafPoliciesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/tenants/$name": {
      id: "/tenants/$name"
      path: "/tenants/$name"
      fullPath: "/tenants/$name"
      preLoaderRoute: typeof TenantsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/sync-secrets/$namespace/$name": {
      id: "/sync-secrets/$namespace/$name"
      path: "/sync-secrets/$namespace/$name"
      fullPath: "/sync-secrets/$namespace/$name"
      preLoaderRoute: typeof SyncSecretsNamespaceNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/routes/$namespace/$name": {
      id: "/routes/$namespace/$name"
      path: "/routes/$namespace/$name"
      fullPath: "/routes/$namespace/$name"
      preLoaderRoute: typeof RoutesNamespaceNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/load-balancers/$namespace/$name": {
      id: "/load-balancers/$namespace/$name"
      path: "/load-balancers/$namespace/$name"
      fullPath: "/load-balancers/$namespace/$name"
      preLoaderRoute: typeof LoadBalancersNamespaceNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/envoy-proxy/$namespace/$name": {
      id: "/envoy-proxy/$namespace/$name"
      path: "/envoy-proxy/$namespace/$name"
      fullPath: "/envoy-proxy/$namespace/$name"
      preLoaderRoute: typeof EnvoyProxyNamespaceNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TenantsNameRoute: TenantsNameRoute,
  WafPoliciesNameRoute: WafPoliciesNameRoute,
  ConfigurationIndexRoute: ConfigurationIndexRoute,
  EnvoyProxyIndexRoute: EnvoyProxyIndexRoute,
  LoadBalancersIndexRoute: LoadBalancersIndexRoute,
  RoutesIndexRoute: RoutesIndexRoute,
  SyncSecretsIndexRoute: SyncSecretsIndexRoute,
  TenantsIndexRoute: TenantsIndexRoute,
  WafPoliciesIndexRoute: WafPoliciesIndexRoute,
  EnvoyProxyNamespaceNameRoute: EnvoyProxyNamespaceNameRoute,
  LoadBalancersNamespaceNameRoute: LoadBalancersNamespaceNameRoute,
  RoutesNamespaceNameRoute: RoutesNamespaceNameRoute,
  SyncSecretsNamespaceNameRoute: SyncSecretsNamespaceNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
